import{applyTimeAtmosphere}from"../parent_time.js";
import{applyParentGreeting}from"../parent_greeting.js";
import{loadParentData}from"../parent_data.js";
import{activateParentAuth}from"../parent_auth.js?v=2";
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(error=>console.warn('NestHome test service worker:',error)));}
let deferredInstallPrompt=null;
const isStandalone=()=>window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;
const isIOS=()=>/iphone|ipad|ipod/i.test(navigator.userAgent);
const isAndroid=()=>/android/i.test(navigator.userAgent);
const isMobile=()=>isIOS()||isAndroid();
function setupInstallPrompt(){const prompt=document.getElementById('installPrompt');const button=document.getElementById('installButton');const close=document.getElementById('installClose');const title=document.getElementById('installTitle');const text=document.getElementById('installText');const iosSteps=document.getElementById('iosSteps');if(!prompt||!button||!close)return;if(isStandalone()){localStorage.setItem('nesthomeInstalled','1');return;}if(!isMobile())return;const show=()=>{prompt.classList.add('is-visible');prompt.setAttribute('aria-hidden','false');};const hide=()=>{prompt.classList.remove('is-visible');prompt.setAttribute('aria-hidden','true');};close.addEventListener('click',hide);button.hidden=true;iosSteps.hidden=true;window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;localStorage.setItem('nesthomeInstalled','1');hide();});if(isIOS()){title.textContent='Add NestHome to your iPhone';text.textContent='Safari uses two quick steps to place NestHome on your Home Screen.';iosSteps.hidden=false;show();return;}window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstallPrompt=event;title.textContent='Add NestHome to your phone';text.textContent='Keep NestHome one tap away and open it without the browser around it.';button.hidden=false;show();});button.addEventListener('click',async()=>{if(!deferredInstallPrompt)return;const installEvent=deferredInstallPrompt;deferredInstallPrompt=null;await installEvent.prompt();const choice=await installEvent.userChoice;if(choice.outcome==='accepted'){localStorage.setItem('nesthomeInstalled','1');hide();}});setTimeout(()=>{if(deferredInstallPrompt)return;title.textContent='Add NestHome to your phone';text.textContent=localStorage.getItem('nesthomeInstalled')==='1'?'NestHome is already installed. Open it from your Home Screen.':'Chrome is not offering the one-tap install on this screen. Tap the ⋮ menu, then choose Add to Home screen or Install app.';button.hidden=true;iosSteps.hidden=true;show();},1800);}
let appStarted=false;
async function startParentApp(){if(appStarted)return;appStarted=true;try{await loadParentData();applyTimeAtmosphere();applyParentGreeting();}catch(error){appStarted=false;console.error("Unable to start NestHome test:",error);}}
setupInstallPrompt();
activateParentAuth(startParentApp);
